### PR TITLE
Remove GtkImageMenuItem usages

### PR DESCRIPTION
**Pull request by antonok-edm**
First(?) step towards a GTK4 port (https://github.com/syncthing-gtk/syncthing-gtk/issues/8)

If you run `syncthing-gtk` with the `G_ENABLE_DIAGNOSTIC=1` environment variable, one of the first warnings that appears is that `GtkImageMenuItem` is deprecated.

It's possible to put images in children of `GtkMenuItem`, but it seems images in menus is [seen as bad practice](https://stackoverflow.com/a/48473708) so I've just removed them altogether instead.

(I haven't removed icon files, in case they'd be useful elsewhere later on)

### CODE REVIEW

**Comment by Salamandar** [comment]
Alright, that's fine with me. Did you see if there are any files that can be deleted with this change ?

**Comment by antonok-edm** [comment]
I believe it's just `eye.svg` and `show_id.svg` - the others were builtin icons

**Comment by A6GibKm** [comment]
it is somewhat fine to have icons in  menus, see https://gitlab.gnome.org/World/secrets/-/blob/master/data/gtk/unlocked_headerbar.ui#L120

image


but in general plain menus are preferable.

**Comment by Salamandar** [comment]
If that helps the GTK4 transition, I’m ok with that. Maybe we will try to add them back afterwards.

**Pull request merged**
