### PR TITLE
Merge Andrewshura's fork without debian directory

### PR DESCRIPTION
**Pull request by Salamandar**
The content of the debian directory should be handled in Debian's repositories. At least for now, until discussions. This is a rebase of @andrewshadura 's branch without adding the `/debian` directory.

### CODE REVIEW

**Comment by andrewshadura** [comment]
I'm afraid you may have looked at a wrong branch, since my fork already had a branch without the debian directory. I'll have a look in a moment.

**Comment by andrewshadura** [comment]
The [`python3-port`](https://salsa.debian.org/debian/syncthing-gtk/-/tree/python3-port) branch (commit [`12a9702d`](https://salsa.debian.org/debian/syncthing-gtk/-/commits/12a9702d)) is the correct branch. I would have force-pushed it here, but I don’t have write access.

**Comment by Salamandar** [comment]
OK, I will change this ! Also, i will add write permissions to this repo. I thought you would have it since it's in the same org, but it looks like only @hrehfeld and @Rudd-O are owners of the org. Could one of you two set us as owners too ? ^^

**Comment by Salamandar** [comment]
Closing in favor of #3

**Pull request closed without merging**
