### PR TITLE
Run isort, autopep8, and then again black

### PR DESCRIPTION
**Pull request by Salamandar**

### CODE REVIEW

**Comment by Rudd-O** [comment]
I would drop 3.8 altogether.

**Comment by Rudd-O** [comment]
Otherwise very nice bro.

**Review by Rudd-O — APPROVED** [review]

**Comment by Salamandar** [comment]
> I would drop 3.8 altogether.

Hmm what are you thinking about specifically when saying that ? ^^

**Comment by Rudd-O** [comment]
Python's about to release 3.12.  Which distros could we not run this that only carry Python 3.8?

**Comment by Salamandar** [comment]
Ah ! I thought this was a remark about some changes i made in this PR ^^

Hmm let's see. https://repology.org/project/python/versions

Debian 11 (stable) has 3.9, so I'd say we can use this as minimum version.

**Pull request merged**
