### PR TITLE
Support building in a venv

### PR DESCRIPTION
**Pull request by antonok-edm**
I tried to build this project in a venv, but I ran into a few problems due to some outdated patterns in `setup.py`. This PR is my attempt to fix those issues.

`data_files` in `setup.py` is [deprecated](https://setuptools.pypa.io/en/latest/references/keywords.html) ([more info](https://github.com/pypa/setuptools/discussions/2648)). When building in a venv, files from `data_files` are not copied to the installation, however `syncthing-gtk` requires some of these files to run properly (`.glade` files, icon files, locale files, plugin scripts). `package_data` is the [modern alternative](https://github.com/pypa/pip/issues/6592), although it doesn't support copying files outside of the package directory (for security reasons), so I've moved those _inside_ of it instead. `data_files` is still used for files that aren't used at runtime (manpages, `.desktop`, etc.) since I'm still not 100% sure what the recommended alternative is for that.

I've also migrated to use `entry_points` rather than `scripts` in `setup.py`. This allows the entrypoint script (previously `scripts/syncthing-gtk`) to be located inside of the `syncthing_gtk` package directory (the new `main.py` file). Bundling runtime resources in the package directory using `package_data` allows some of the runtime path checks to be simplified - see changes in `main.py` and `uisettingsdialog.py`.

Right now it builds and launches without any visible problems, although I haven't tested all functionality and packaging methods so I suspect this still requires some work. Notably:
- There might be more complexity to the `icons` directory than I accounted for so far, I haven't thoroughly checked how the code uses them
- Building/packaging on Windows is still a mystery to me so I haven't touched any of that
- I've also never tried building an AppImage before, so that might need some changes too

### CODE REVIEW

**Comment by Salamandar** [comment]
I didn't have time to review the PR yet but just know this app is supposed to be built with Meson, not python build. The main reason is that we need to install files outside of site-package and it doesn't support that (as you said). 
I'll review the pr when i'm back home though.

**Comment by eli-schwartz** [comment]
> `data_files` is still used for files that aren't used at runtime (manpages, `.desktop`, etc.) since I'm still not 100% sure what the recommended alternative is for that.

This is entirely impossible to be handled via the python packaging system. There is no valid location for them in a venv. None at all. They need to be integrated into the operating system, and the entire point of a venv is to be sandboxed *away* from the operating system.

Arguably icon themes are the same way. At a minimum, syncthing-gtk.png *must* be located in /usr/share/icons & /usr/share/pixmaps in order for the OS to validly apply that icon to the desktop file / menu launcher.

**Comment by Salamandar** [comment]
@antonok-edm i'm sorry but we're going to close this :(

Thanks for the work though <3

**Comment by antonok-edm** [comment]
Looks like the README got some info on how to build in https://github.com/syncthing-gtk/syncthing-gtk/commit/e875b613181affa4c6171118b355d8e4e5e48ae4 - that works well enough for me :smile:

**Comment by Salamandar** [comment]
Yes indeed ! Your PR made me realize it was missing some info :)

**Pull request closed without merging**
