### PR TITLE
Python3 port (@andrewshura's port)

### PR DESCRIPTION
**Pull request by Salamandar**
Let's review together this branch.

### CODE REVIEW

**Comment by Salamandar** [comment]
@andrewshadura Can you explain the rationale for 342b00d69b618e86ab59bcc5021303ce00f1d075 (Drop support for icons in menus) ? It looks to me like a feature drop.

**Comment by andrewshadura** [comment]
Icons in menus have been long deprecated across all platforms (Gnome, Windows; Mas OS probably never had them) and having them configurable introduces complexity that otherwise could have been avoided. As you may have noticed, the Glade/UI files use non-standard conditionals: removing configurable icons in menus reduces the number of them, making it possible to eventually get rid of the conditionals altogether.

**Comment by Salamandar** [comment]
Those commits might be better in other MRs:
* ae7e56c30164c4a639d42699cddb36f05aba120c (Reshuffle menu items to better match GNOME HIG)
* 061224eba702c2a00f582973d2bed65e03ca32de (Add a list of folders to the appindicator menu)
* e7caac299646f0e098176c9f907f61900fa4d501 (Reformat code according to PEP8 and sort imports) -> Quite a huge and difficult to read in the same PR as the rest of the work
* 97e969b06cdb04c713bd3d3e045e873d56f0e878 (Fix flake8 issues) -> Same
* 4a19b10fdee9963382368ed413568b35f3cb7280 (Rename glade/*.glade to ui/*.ui)

I reviewed the rest and it looks a-ok to me !

**Comment by Salamandar** [comment]
> Icons in menus have been long deprecated across all platforms, and having them configurable introduces complexity that otherwise could have been avoided. As you may have noticed, the Glade/UI files use non-standard conditionals: removing configurable icons in menus reduces the number of them, making it possible to eventually get rid of the conditionals altogether.

As I read your answer I realized it's not about icons in buttons! So yeah, OK with me.

**Comment by andrewshadura** [comment]
> Those commits might be better in other MRs:

Well, they surely could have been — they accumulated over a long time, you know 🙂

**Comment by Salamandar** [comment]
I'll rebase this branch to remove those commits and incorporate them later.

**Review by Salamandar — COMMENTED** [review]
Can't approve as I authored the PR, but LGTM. I'm waiting a bit for @hrehfeld or @Rudd-O to drop by before merging.

**Comment by Rudd-O** [comment]
I defer to @hrehfeld 's assessment here.

**Comment by Salamandar** [comment]
Not sure if @hrehfeld is active anymore…

**Comment by hrehfeld** [comment]
Sorry, I was crunching :-)

Awesomely atomic commits, was a blast to review! Almost everything looks fine, I'm wondering about these:
- https://github.com/syncthing-gtk/syncthing-gtk_reforked/pull/3/commits/41baf387f51b67d1c7990f6973b8a44c4d397405 is `icon-size=1` a sensible work-around?
- https://github.com/syncthing-gtk/syncthing-gtk_reforked/pull/3/commits/1736f7e1b90d8e88a52df5877ed49603e34536fb#diff-6944dfb198df39edf2a2adebc3dadf470c78d4e382d0a5cc5ab7cbd0ac7dee18R677 the first arg of `socket.socket.listen() `  [_"specifies the number of unaccepted connections that the system will allow before refusing new connections. If not specified, a default reasonable value is chosen."_](https://docs.python.org/3/library/socket.html#socket.socket.listen) Is 0 correct in this  context? Can we just drop the arg?
- https://github.com/syncthing-gtk/syncthing-gtk_reforked/pull/3/commits/254720ee9db2daa93a0646eb30b4d48b12ea05fa does this incorrectly reintroduce py2 compatability code?

Feel free to merge if my questions are irrelevant or when they're resolved.:+1::+1:

**Comment by andrewshadura** [comment]
> 254720e does this incorrectly reintroduce py2 compatability code?

Probably a mismerge, I’ll double-check.

**Comment by andrewshadura** [comment]
> Is 0 correct in this context? Can we just drop the arg?

Probably we can drop it.

**Comment by Salamandar** [comment]
> > Is 0 correct in this context? Can we just drop the arg?
> 
> Probably we can drop it.

Dropped in 0edd6c98d25bec6c153f5e0aa8be4d6381b3a60b

**Comment by Salamandar** [comment]
> [41baf38](https://github.com/syncthing-gtk/syncthing-gtk_reforked/commit/41baf387f51b67d1c7990f6973b8a44c4d397405) is `icon-size=1` a sensible work-around?

In fact according to https://docs.gtk.org/gtk3/enum.IconSize.html 3 should be better (GTK_ICON_SIZE_LARGE_TOOLBAR | Size appropriate for large toolbars (24px)).

I'll fix this in another commit.

**Comment by Salamandar** [comment]
> https://github.com/syncthing-gtk/syncthing-gtk_reforked/commit/254720ee9db2daa93a0646eb30b4d48b12ea05fa does this incorrectly reintroduce py2 compatability code?

Ooops that looks like it might be my fault. Fixed.

**Comment by Rudd-O** [comment]
Please use the symbolics instead of integers when setting up properties like that.

**Comment by Salamandar** [comment]
> Please use the symbolics instead of integers when setting up properties like that.

Doesn't look like it's doable : https://stackoverflow.com/questions/64628336/gtk-ui-with-xml-how-to-put-enum-values-in-fields

Also I just tried doing the same thing in Glade and it puts the integer value 3, not a named value.

**Comment by Rudd-O** [comment]
When you do it in Python it is totally doable.  It's fine if the UI file keeps the integer.

**Comment by Salamandar** [comment]
Ah alright :)

Is it ok for you to merge as is ? I think we plan to revanp the whole glade files anyways, maybe as a redesign step.

**Comment by Rudd-O** [comment]
Fine with me.  Proceed at your leisure.

**Comment by Rudd-O** [comment]
Have we already blackened the codebase?  We should.

**Comment by Salamandar** [comment]
> Have we already blackened the codebase? We should.

Nope, It should come in a next PR. I wanted to keep this one as minimal as possible while still keeping @andrewshadura's work.

**Comment by Salamandar** [comment]
> Fine with me. Proceed at your leisure.

Cool :D

Would it be possible to give us ownership over the syncthing-gtk org ? I'd want to swap the 2 repositories once this PR is merged.

**Comment by Rudd-O** [comment]
Am I an owner?  Let me check.

**Comment by Rudd-O** [comment]
Alright.  You and @andrewshadura are now owners too.

**Comment by Salamandar** [comment]
Thank you !

**Pull request merged**
