### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by Salamandar**
Basically: move files to the `packaging` subdirectory.

PS : will need to change the target branch once cleanup is merged

### CODE REVIEW

**Comment by Rudd-O** [comment]
Cool.  I hope to contribute a specfile soon.

**Comment by Rudd-O** [comment]
Please fix CI issues, ensure the packaging actually does build in CI, and then you should merge.

**Review by Rudd-O — APPROVED** [review]
Approval conditional to CI issues fixed.

**Comment by Salamandar** [comment]
> Please fix CI issues, ensure the packaging actually does build in CI, and then you should merge.

Unfortunately Pylint won't pass in the near future. Also Pylint doesn't like Gobject-introspection :
https://stackoverflow.com/questions/71878529/pylint-and-vscode-do-not-find-pygobject-class-members
https://github.com/PyCQA/pylint/issues/6352
(those are issues i'm reproducing locally)
I think those cases will be handled via pylint pragmas.

**Comment by Salamandar** [comment]
FYI this branch is building a working MSI for a non-working Syncthing-gtk installation (without python, without dependencies etc.). It's still WIP.

**Comment by Rudd-O** [comment]
Then proceed either way.

**Pull request merged**
